- name: Gather CPU RAM and Disk Space Usage
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: CPU usage
      ansible.builtin.shell: top -bn1 | grep 'Cpu(s)' | awk '{print $2}'
      register: cpu_usage

    - name: Linux Version
      ansible.builtin.shell: cat /etc/redhat-release
      register: version_rhel

    - name: RAM Usage
      ansible.builtin.shell: top -bn1 | awk '/MiB Mem/ {printf "%.2f\n", $8/$4 * 100}'
      register: ram_usage

    - name: Gather Disk Space
      ansible.builtin.shell: "df -h --output=pcent / | awk 'NR==2 {print $1}'"
      register: disk_space

    - name: Usage Stats
      ansible.builtin.debug:
        msg: 
          - "Executed On: {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}"
          - "CPU Usage: {{ cpu_usage.stdout }}%"
          - "RAM Usage: {{ ram_usage.stdout }}%"
          - "Disk Space Used: {{ disk_space.stdout }}"
          - "Linux Version: {{ version_rhel.stdout }}"         

    - name: Check DB connection
      community.general.mssql_script:
        login_user: "prueba"
        login_password: "10Constanza#"
        login_host: "10.0.0.13"
        login_port: "1433"
        db: "BACtest"
        script: "SELECT * from linuxtest"
      register: out_database
      delegate_to: localhost

    - name: Usage Stats
      ansible.builtin.debug:
        msg: "{{ out_database }}" 
      
