---
- name: Generar archivo en la máquina rhel
  hosts: localhost
  tasks:
  
  - name: crear archivo
    shell: hotstname
    register: local_host

  - name: print hostname
    debug:
      msg: "{{ local_host.stdout_lines }}"

  - set_stats:
    data:
      list_host: "{{ local_host.stdout_lines }}"
    
