---
- name: conexion maquinas windows
  hosts: all
  tasks:
    - name: windows ping
      ansible.windows.win_ping:
      register: registro_ping

    - name: print resultados
      ansible.built.debug:
        msg: "{{ registro_ping }} "
