---
- name: conexion maquinas windows
  hosts: all
  tasks:
    - name: windows ping
      win_ping:
      register: ping-out

    - name: print resultados
      debug:
        msg: "{{ ping-out.stdout_lines }} "
