---
- name: conexion maquinas windows
  hosts: all
  tasks:
    - name: windows ping
      win_ping:
      register: registro_ping

    - name: list volume
      win_shell: Get-Volume
      register:unidades

    - name: print resultados
      debug:
        msg: 
        - "{{ registro_ping }}"
        - "{{ unidades }}"
