---
- name: conexion maquinas windows
  hosts: all
  tasks:
    - name: windows ping
      win_ping:
      register: registro_ping

    - name: list volume
      win_command: powershell.exe Get-Volume
      register:unidades

    - name: print resultados
      debug:
        msg: "{{ unidades }}"
        
       
