---
- name: conexion maquinas windows
  hosts: all
  tasks:
    - name: windows ping
      win_ping:
      register: registro_ping

    - name: print resultados
      debug:
        msg: "{{ registro_ping.stdout_lines }} "
